### ISSUE TITLE
Launcher endpoints

### ISSUE THREAD

**Issue by Shaggy84675** [Deathgarden-Rebirth/Deathgarden_Rebirth-Rewrite#36]
- [x] Version
- [x] News title + url link

Please put into route api v1 group

**Comment by Vari7921** [comment]
I created the endpoints you wanted.

## Launcher Version
The launcher version can be retrieved via `/api/v1/launcher-version`. It is set inside the .env with `LAUNCHER_VERSION`
The endpoints just returns the string that is set there as the body, nothing more.

## Launcher Message
The launcher message can be edited via the admin panel. (It uses the same permission as the File manager).
The endpoint for retrieving the message is `/api/v1/launcher-message`.
The Response looks like this:
```json
{
  "message": "message",
  "url": "url"
}
```
If there is no message set it returns just `null`. The `url` property is also nullable.

I also added both requests to Bruno so you can test them there.
